apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8srequiredlabelmatchnamespace
spec:
  crd:
    spec:
      names:
        kind: K8sRequiredLabelMatchNamespace
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8srequiredlabelmatchnamespace

        required_label := "someLabel"

        resource_labels := object.get(input.review.object.metadata, "labels", {})
        ns_labels := object.get(input.review.namespace.metadata, "labels", {})

        # 1. Resource is missing `labels` or `someLabel`
        violation[{"msg": msg}] {
          not resource_labels["someLabel"]
          msg := "Missing 'someLabel' label on the resource"
        }

        # 2. Namespace is missing `labels` or `someLabel`
        violation[{"msg": msg}] {
          not ns_labels[required_label]
          msg := sprintf("Missing 'someLabel' label on the namespace, namespace labels: %v", [ns_labels])
        }

        # 3. Ensure `someLabel` label should match between resource and namespace
        violation[{"msg": msg}] {
          resource_labels[required_label] != ns_labels[required_label]
          msg := sprintf("Mismatch 'someLabel' label between resource and namespace, resource labels: %v, namespace labels: %v", [resource_labels, ns_labels])
        }